### PR TITLE
Name: Abhishek Kumar "added file in Diwali folder"

### PR DESCRIPTION
**Pull request by Abhishek-00**

### CODE REVIEW

**Review by savneetkaur03 — CHANGES_REQUESTED** [review]
Please add the correct logo

**Comment by Abhishek-00** [comment]
> Please add the correct logo
which one?

**Comment by ShaileshKumar007** [comment]
Use the logos from the Assets folder

**Comment by ShaileshKumar007** [comment]
I'm closing this PR

**Pull request closed without merging**
